name: CI/CD Pipeline

on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Set permissions for gradlew
        run: |
          chmod +x demo/gradlew

      - name: Build Java application
        run: |
          cd demo
          ./gradlew build

      - name: List the contents of the build directory
        run: ls -la  demo/build/libs/

  build_and_push:
    needs: unit_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages Docker registry
        run: echo "${{ secrets.MY_GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u JesperSchon --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]')
          docker build -t docker.pkg.github.com/JesperSchon/to-do-list-grupp-7-enskild/min-app:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          IMAGE_TAG=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]')
          docker push docker.pkg.github.com/JesperSchon/To-Do-List-Grupp-7-Enskild/min-app:$IMAGE_TAG

  fake_deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Fake Deploy to Test Environment
        run: |
          IMAGE_TAG=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]')
          echo "Deploying image docker.pkg.github.com/JesperSchon/To-Do-List-Grupp-7-Enskild/min-app:$IMAGE_TAG"